# Generated by Django 3.2.11 on 2022-12-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('medical_history', models.TextField()),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('blood_grp', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('mob_no', models.CharField(max_length=50)),
                ('offer', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
