# Generated by Django 3.2.11 on 2022-12-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='medical_history',
            field=models.TextField(null=True),
        ),
    ]
