# Generated by Django 3.2.11 on 2022-12-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_users_medical_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
