# Generated by Django 3.2.11 on 2023-02-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('mob_no', models.CharField(max_length=50)),
                ('Speciality', models.TextField(null=True)),
                ('date', models.DateField()),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
